/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.JOptionPane;
import modelo.usuarios;

/**
 *
 * @author USER
 */
public class bancoPrincipal extends javax.swing.JFrame {

    private usuarios persona;
    public bancoPrincipal() {
        this.setTitle("Cow´s Bank");
        this.setSize(600,700);
        this.setResizable(false); 
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);      
        this.setLocationRelativeTo(null);
        initComponents();   
    }
    
    public void setPersona(usuarios persona){
        this.persona=persona;
    }
    
    public void setDinero(){
        etiquetaSaldoNumero.setText(String.valueOf(persona.getDinero()));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelBanco = new javax.swing.JPanel();
        etiquetaSaldo = new javax.swing.JLabel();
        btnConsignar = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        etiquetaSaldoNumero = new javax.swing.JLabel();
        etiquetaImagen = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaSaldo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaSaldo.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaSaldo.setText("Tu saldo");
        panelBanco.add(etiquetaSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 90, 40));

        btnConsignar.setText("Consignar");
        panelBanco.add(btnConsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, -1, -1));

        btnRetirar.setText("Retirar");
        panelBanco.add(btnRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 90, -1));

        etiquetaSaldoNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiquetaSaldoNumero.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaSaldoNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaSaldoNumero.setText("0.0");
        panelBanco.add(etiquetaSaldoNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 70, -1));

        etiquetaImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoBanco.jpg"))); // NOI18N
        panelBanco.add(etiquetaImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 604, 704));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bancoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bancoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bancoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bancoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable(){
            
            public void run() {  
                new bancoPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConsignar;
    public javax.swing.JButton btnRetirar;
    private javax.swing.JLabel etiquetaImagen;
    private javax.swing.JLabel etiquetaSaldo;
    public javax.swing.JLabel etiquetaSaldoNumero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelBanco;
    // End of variables declaration//GEN-END:variables
}
