/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Color;

/**
 *
 * @author USER
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        this.setVisible(true);
        this.setSize(600,700);
        this.setTitle("Cow´s Bank");
        this.setResizable(false); 
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);        
        this.setLocationRelativeTo(null);  
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaHeader = new javax.swing.JLabel();
        etiquetaParrafo = new javax.swing.JLabel();
        botonRegistro = new javax.swing.JButton();
        botonInicio = new javax.swing.JButton();
        etiquetaImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaHeader.setFont(new java.awt.Font("MingLiU-ExtB", 0, 36)); // NOI18N
        etiquetaHeader.setForeground(new java.awt.Color(204, 255, 204));
        etiquetaHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaHeader.setText("Cow´s Bank");
        getContentPane().add(etiquetaHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 220, 70));

        etiquetaParrafo.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        etiquetaParrafo.setForeground(new java.awt.Color(204, 255, 204));
        etiquetaParrafo.setText("<html>Tú te encargas de imaginarlo, nosotros de hacerlo realidad<html>");
        getContentPane().add(etiquetaParrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 280, 150));

        botonRegistro.setBackground(new java.awt.Color(153, 153, 255));
        botonRegistro.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        botonRegistro.setForeground(new java.awt.Color(0, 0, 0));
        botonRegistro.setText("Registrarse");
        botonRegistro.setBorder(null);
        botonRegistro.setBorderPainted(false);
        botonRegistro.setContentAreaFilled(false);
        botonRegistro.setFocusable(false);
        botonRegistro.setOpaque(true);
        botonRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistroMouseExited(evt);
            }
        });
        getContentPane().add(botonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 200, 50));

        botonInicio.setBackground(new java.awt.Color(153, 153, 255));
        botonInicio.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        botonInicio.setForeground(new java.awt.Color(0, 0, 0));
        botonInicio.setText("Iniciar sesión");
        botonInicio.setBorder(null);
        botonInicio.setBorderPainted(false);
        botonInicio.setContentAreaFilled(false);
        botonInicio.setFocusable(false);
        botonInicio.setOpaque(true);
        botonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonInicioMouseExited(evt);
            }
        });
        getContentPane().add(botonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 200, 50));
        botonInicio.getAccessibleContext().setAccessibleDescription("");

        etiquetaImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal.jpg"))); // NOI18N
        getContentPane().add(etiquetaImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseEntered
        botonInicio.setBackground(new Color(99,77,205));
    }//GEN-LAST:event_botonInicioMouseEntered

    private void botonInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseExited
        botonInicio.setBackground(new Color(153, 153, 255));
    }//GEN-LAST:event_botonInicioMouseExited

    private void botonRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroMouseEntered
        botonRegistro.setBackground(new Color(99,77,205));
    }//GEN-LAST:event_botonRegistroMouseEntered

    private void botonRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroMouseExited
         botonRegistro.setBackground(new Color(153, 153, 255));
    }//GEN-LAST:event_botonRegistroMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ventanaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonInicio;
    public javax.swing.JButton botonRegistro;
    private javax.swing.JLabel etiquetaHeader;
    private javax.swing.JLabel etiquetaImagen;
    private javax.swing.JLabel etiquetaParrafo;
    // End of variables declaration//GEN-END:variables
}
